### ISSUE TITLE
Typo where constant should follow config variable?

### ISSUE THREAD

**Issue by NicksonYap** [ppwwyyxx/OpenPano#105]
Was going through the source code and found this line

https://github.com/ppwwyyxx/OpenPano/blob/ed87d3ce1fe5762c230ca48d4e3832814ccde9d5/src/stitch/transform_estimate.cc#L46

It's quite weird for the number 800 to appear here only
Probably it should be replaced with SIFT_WORKING_SIZE?
I'm really unsure

https://github.com/ppwwyyxx/OpenPano/blob/ed87d3ce1fe5762c230ca48d4e3832814ccde9d5/src/config.cfg#L19

Such that it from:

```c++
ransac_inlier_thres = (shape1.w + shape1.h) * 0.5 / 800 * RANSAC_INLIER_THRES;
```

to:

```c++
ransac_inlier_thres = (shape1.w + shape1.h) * 0.5 / SIFT_WORKING_SIZE * RANSAC_INLIER_THRES;
```

**Comment by ppwwyyxx** [comment]
The 800 here is unrelated to `SIFT_WORKING_SIZE`. It's merely a parameter and it can already be tuned by tuning `RANSAC_INLIER_THRES`.
