### ISSUE TITLE
请问拼接的图形出现重影能处理么

### ISSUE THREAD

**Issue by SJJ-dot** [ppwwyyxx/OpenPano#114]
能不将照片重叠的地方去掉，从重叠中间位置剪切直接拼起来
原始图片：
![DJI_0487](https://user-images.githubusercontent.com/15243969/118209462-3b22d080-b49b-11eb-9d5d-ac8ef6e3c211.JPG)
![DJI_0488](https://user-images.githubusercontent.com/15243969/118209465-3cec9400-b49b-11eb-9a34-ac685f4f68d7.JPG)
输出：
![out1](https://user-images.githubusercontent.com/15243969/118209531-5b528f80-b49b-11eb-95d2-15e608f9ff3b.jpg)

**Comment by perfectboy666** [comment]
不能
