### ISSUE TITLE
error:Failed to find  hfactor

### ISSUE THREAD

**Issue by Yuanyuanyuan2020** [ppwwyyxx/OpenPano#119]
I  want to use the CYLINDER mode , so I set ` CYLINDER 1 , ESTIMATE_CAMERA 0` on config.cfg ,The test images are 38 picture of the Carnegie Mellon University in the example folder. but the program reported the error: Failed to find  hfactor.

OS : ubuntu20.4

(base) yuanyuan@yuanyuan-All-Series:~/Image-stitching/src$ ./image-stitching medium00.JPG medium01.JPG medium02.JPG medium03.JPG medium04.JPG medium05.JPG medium06.JPG medium07.JPG medium08.JPG medium09.JPG medium10.JPG medium11.JPG medium12.JPG medium13.JPG medium14.JPG medium15.JPG medium16.JPG medium17.JPG medium18.JPG medium19.JPG medium20.JPG medium21.JPG medium22.JPG medium23.JPG medium24.JPG medium25.JPG medium26.JPG medium27.JPG medium28.JPG medium29.JPG medium30.JPG medium31.JPG medium32.JPG medium33.JPG medium34.JPG medium35.JPG medium36.JPG medium37.JPG
[init_config@main.cc:248] Run with cylinder mode.
[calc_feature@stitcherbase.cc:22] Image 1 has 744 features
[calc_feature@stitcherbase.cc:22] Image 0 has 807 features
[calc_feature@stitcherbase.cc:22] Image 4 has 2330 features
[calc_feature@stitcherbase.cc:22] Image 2 has 1294 features
[calc_feature@stitcherbase.cc:22] Image 8 has 1413 features
[calc_feature@stitcherbase.cc:22] Image 7 has 1414 features

[calc_feature@stitcherbase.cc:22] Image 10 has 2134 features
[calc_feature@stitcherbase.cc:22] Image 5 has 2461 features
[calc_feature@stitcherbase.cc:22] Image 3 has 2305 features
[calc_feature@stitcherbase.cc:22] Image 6 has 2365 features
[calc_feature@stitcherbase.cc:22] Image 9 has 1505 features
[calc_feature@stitcherbase.cc:22] Image 11 has 2325 features
[calc_feature@stitcherbase.cc:22] Image 12 has 2439 features
[calc_feature@stitcherbase.cc:22] Image 16 has 385 features
[calc_feature@stitcherbase.cc:22] Image 15 has 866 features
[calc_feature@stitcherbase.cc:22] Image 14 has 1203 features
[calc_feature@stitcherbase.cc:22] Image 13 has 1515 features
[calc_feature@stitcherbase.cc:22] Image 17 has 1075 features
[calc_feature@stitcherbase.cc:22] Image 21 has 1129 features
[calc_feature@stitcherbase.cc:22] Image 18 has 1670 features
[calc_feature@stitcherbase.cc:22] Image 22 has 1225 features
[calc_feature@stitcherbase.cc:22] Image 19 has 2472 features
[calc_feature@stitcherbase.cc:22] Image 20 has 1950 features
[calc_feature@stitcherbase.cc:22] Image 23 has 1976 features
[calc_feature@stitcherbase.cc:22] Image 26 has 1175 features
[calc_feature@stitcherbase.cc:22] Image 29 has 644 features
[calc_feature@stitcherbase.cc:22] Image 27 has 1278 features
[calc_feature@stitcherbase.cc:22] Image 25 has 1906 features
[calc_feature@stitcherbase.cc:22] Image 28 has 969 features
[calc_feature@stitcherbase.cc:22] Image 24 has 2251 features
[calc_feature@stitcherbase.cc:22] Image 30 has 681 features
[calc_feature@stitcherbase.cc:22] Image 32 has 1351 features
[calc_feature@stitcherbase.cc:22] Image 31 has 1659 features
[calc_feature@stitcherbase.cc:22] Image 34 has 1129 features
[calc_feature@stitcherbase.cc:22] Image 33 has 890 features
[calc_feature@stitcherbase.cc:22] Image 35 has 977 features
[calc_feature@stitcherbase.cc:22] Image 36 has 1762 features
[calc_feature@stitcherbase.cc:22] Image 37 has 1772 features
calc_feature(): 1747.517000 milliseconds.
BuildTrees: 138.857000 milliseconds.
[build_warp@cylstitcher.cc:43] match time: 0.426873 secs
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.736842,0.049296, r2mr2p: 0.608696,0.017136
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.737374,0.064659, r2mr2p: 0.737374,0.130357
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=507012, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.620690,0.103647, r2mr2p: 0.635294,0.147139
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=511012, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.547945,0.116618, r2mr2p: 0.540541,0.081800
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=542288, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.652174,0.106195, r2mr2p: 0.625000,0.079893
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=748912, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.532609,0.089744, r2mr2p: 0.544444,0.098394
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=736505, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.561753,0.117992, r2mr2p: 0.573171,0.120823
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=550523, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.611607,0.164466, r2mr2p: 0.643192,0.155153
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=555181, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.481132,0.105663, r2mr2p: 0.479624,0.105082
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=673339, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.621094,0.163077, r2mr2p: 0.574007,0.149859
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=651404, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.464548,0.088702, r2mr2p: 0.465686,0.110787
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=888277, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.648438,0.113543, r2mr2p: 0.658730,0.121701
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=676441, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.694915,0.112022, r2mr2p: 0.672131,0.061469
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=567494, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.574879,0.119119, r2mr2p: 0.577670,0.118408
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=551571, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.662162,0.094412, r2mr2p: 0.653333,0.116945
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=616299, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 12.500000,0.757576, r2mr2p: 0.765306,0.109489
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=490322, ImageArea=1046994
[fill_inliers_to_matchinfo@transform_estimate.cc:198] r1mr1p: 0.553571,0.093939, r2mr2p: 0.556054,0.117871
[fill_inliers_to_matchinfo@transform_estimate.cc:206] OverlapArea=657102, ImageArea=1046994
error: Failed to find hfactor

**Comment by ppwwyyxx** [comment]
As README says, cylinder mode expects:
> You are only turning left (or right) when taking the images (as is usually done), no translations or other type of rotations allowed.
Images are taken with the same camera, with a known FOCAL_LENGTH set in config.
Images are given in the left-to-right order. (I might fix this in the future)

So the failure is expected
