### ISSUE TITLE
after CylinderWarper, it becames fuzzy

### ISSUE THREAD

**Issue by SanjunLiu** [ppwwyyxx/OpenPano#24]

**Comment by ppwwyyxx** [comment]
Could you provide the input you're using, the exact steps you've taken, the unexpected output you've seen, and explain why it is unexpected (if not obvious to others).
Otherwise no one can do anything about it. Thanks.

**Comment by SanjunLiu** [comment]
Thanks for  your apply very much!
What we have test is the part of "warp" based on Cylinder with factor 1.0.
the origin image as follows:
![medium00](https://cloud.githubusercontent.com/assets/15029439/20915104/c7ace2be-bbbe-11e6-9638-f3ec4c360d7c.JPG)

after warping, it becomes a little blurred when you check it on the right-bottom carefully:
![warp2](https://cloud.githubusercontent.com/assets/15029439/20915151/017d3e80-bbbf-11e6-8349-23e759c2c6dc.jpg)

**Comment by ppwwyyxx** [comment]
I see. The warping includes a bilinear sampling step which could cause some blur.
