### ISSUE TITLE
Buggy while building

### ISSUE THREAD

**Issue by jiapei100** [ppwwyyxx/OpenPano#29]
Hi:

> 
> In file included from ......OpenPano/src/feature/feature.hh:10:0,
>                  from ......OpenPano/src/feature/matcher.hh:8,
>                  from ......OpenPano/src/feature/matcher.cc:7:
> ......OpenPano/src/./feature/dist.hh: In instantiation of ‘float pano::L2SSE::operator()(Iterator1, Iterator2, size_t, pano::L2SSE::ResultType) const [with Iterator1 = float*; Iterator2 = double*; size_t = long unsigned int; pano::L2SSE::ResultType = float]’:
> /usr/include/flann/algorithms/kmeans_index.h:586:45:   required from ‘void flann::KMeansIndex<Distance>::computeClustering(flann::KMeansIndex<Distance>::NodePtr, int*, int, int) [with Distance = pano::L2SSE; flann::KMeansIndex<Distance>::NodePtr = flann::KMeansIndex<pano::L2SSE>::Node*]’
> /usr/include/flann/algorithms/kmeans_index.h:344:26:   required from ‘void flann::KMeansIndex<Distance>::buildIndexImpl() [with Distance = pano::L2SSE]’
> ......OpenPano/src/feature/matcher.cc:146:1:   required from here
> ......OpenPano/src/./feature/dist.hh:29:31: error: cannot convert ‘double*’ to ‘const float*’ for argument ‘2’ to ‘float pano::euclidean_sqr(const float*, const float*, size_t, float)’
>      return pano::euclidean_sqr(a, b, size, worst_dist);
>                                ^
> CMakeFiles/image-stitching.dir/build.make:206: recipe for target 'CMakeFiles/image-stitching.dir/feature/matcher.cc.o' failed
> make[2]: *** [CMakeFiles/image-stitching.dir/feature/matcher.cc.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/image-stitching.dir/all' failed
> make[1]: *** [CMakeFiles/image-stitching.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 
>

Met the above bug during building....

Suggestions?

Pei

**Comment by ppwwyyxx** [comment]
Each commit of the project is built automatically on [travis](https://travis-ci.org/ppwwyyxx/panorama) with a clean ubuntu installation.

From the log it looks like it's using flann from your system (/usr/include/flann). Do you know which version of flann it is? The code here should work with the flann it included, but I'm not sure about other version of flann.
