### ISSUE TITLE
Failed using TRANS mode

### ISSUE THREAD

**Issue by miller233** [ppwwyyxx/OpenPano#33]
hi,
  I always got this error while using the TRANS mode : "assertion "lu.isInvertible()" failed, in inverse".  I am sure that the images has only translate movement, what could be the problem ? is there any advice?

Miller

**Comment by ppwwyyxx** [comment]
It failed to find a homography between a pair of images. It may because two images are too different, or feature less, or nearly identical, or other reasons I can't think of. It's hard to tell without seeing the data.

**Comment by mahxn0** [comment]
whatever image input,i also always got the error using this mode;  used to be able to stitch the picture
![1](https://cloud.githubusercontent.com/assets/19154155/23355572/5103eb50-fd11-11e6-8091-02faae58e766.jpg)
![2](https://cloud.githubusercontent.com/assets/19154155/23355573/510428b8-fd11-11e6-942d-e3273163c9d2.jpg)
![3](https://cloud.githubusercontent.com/assets/19154155/23355575/51510110-fd11-11e6-9346-b5fcca15f7a0.jpg)
![4](https://cloud.githubusercontent.com/assets/19154155/23355574/514c62fe-fd11-11e6-818b-28c4d2f92b88.jpg)

**Comment by ppwwyyxx** [comment]
If it fails for the sample data then it should be a bug. I'll take a look.
