### ISSUE TITLE
The output of image is bit blurry

### ISSUE THREAD

**Issue by pritasam** [ppwwyyxx/OpenPano#38]
I notices the text and some places in image  are bit blurry.....Can you suggest me what is causing it ? any settings? in config file I tried to change few parameters but did not work.....

I captured images according to instructions....The overall stitching is good but the image is bit blur specially text...

I tried the opencv stitcher it sometimes fails to stitch but the quality is very good ......

**Comment by ppwwyyxx** [comment]
Could you post your images?

**Comment by pritasam** [comment]
Hi you can download them https://www.sendspace.com/file/yswhg1

**Comment by ppwwyyxx** [comment]
Usually it doesn't work well for objects that are too close.

**Comment by pritasam** [comment]
So How can I address this means any other way ? I like this library...but I want to take close pictures

**Comment by ppwwyyxx** [comment]
For close objects any small movement of camera lens affects quality significantly.
You need to try to keep lens position more static when rotating the camera.

**Comment by pritasam** [comment]
It is bit difficult to keep the camera lens position stable....Actually the problem I see is only with text it is creating shadow of it text other components are looking good even the bold large text...Can I address this problem anyhow ?

**Comment by HYPJUDY** [comment]
The example result image [flower.jpg](https://github.com/ppwwyyxx/OpenPano/blob/master/results/flower.jpg) is blurry too. Its source images (1-4.jpg) actually close to each other and three of then (e.g. 1,2,4.jpg) are enough to stitch a full image. Btw,  are these source photos taken by stable rotating camera?

**Comment by ppwwyyxx** [comment]
They are not.
