### ISSUE TITLE
multiband blending result in some highlight spot

### ISSUE THREAD

**Issue by riyueshi** [ppwwyyxx/OpenPano#41]
Hi,
    I tried to perform multiband blending while stitching image using opencv. but sometime the result got weird, the stitched image got some highlight spot (as image below). And the spot seems occurred near the cross of seam. Is there any idea what is the reason lead to this effect. 

![multiband](https://user-images.githubusercontent.com/8179788/29015352-3ef8c762-7b80-11e7-97c7-3d085732cb56.PNG)

Miller

**Comment by ppwwyyxx** [comment]
I don't know how opencv implements this. In terms of algorithm, if the original photos are consistent in color (e.g. exposure time) this shouldn't happen.

**Comment by riyueshi** [comment]
The photos are consistent in color in this data set.  I would like to work on the opencv source code.
Thanks.
