### ISSUE TITLE
Compilation problems about cimg

### ISSUE THREAD

**Issue by Springlee-P** [ppwwyyxx/OpenPano#44]
Hello, thank you very much for your code
I had the following error during compilation
![image](https://user-images.githubusercontent.com/27715556/30893817-ba9b81c4-a372-11e7-822f-abe4991a2cc1.png)
The compilation environment is VS2015. Do you have any good solutions?Is it still needed?

**Comment by ppwwyyxx** [comment]
During configuration it should've printed message such as libjpeg not found.
Basically you need to have libjpeg in your system and let cmake find it. Although I don't know how this is done in VS.

**Comment by Springlee-P** [comment]
Libjpeg already sets the environment variable and cmake is ok . The exe times error was generated in vs2015

**Comment by Springlee-P** [comment]
Does this have anything to do with the 32-bit 64-bit system?

**Comment by ppwwyyxx** [comment]
You need a libjpeg built with the same architecture of your target executable.

**Comment by Springlee-P** [comment]
Ok, let me check,
Also, can this be compiled into a dynamic link library?

**Comment by ppwwyyxx** [comment]
It will be compiled to a dynamic link library and an executable.

**Comment by Springlee-P** [comment]
Can this project bring in opencv?

**Comment by ppwwyyxx** [comment]
You can add opencv if you need.

**Comment by Springlee-P** [comment]
I referenced it in the image-stitching project, but in openpano, compilation doesn't go through how to refer to opencv in the static library project (openpano)

**Comment by ppwwyyxx** [comment]
Could you follow the documentation: https://docs.opencv.org/3.3.0/db/df5/tutorial_linux_gcc_cmake.html
