### ISSUE TITLE
Splicing error

### ISSUE THREAD

**Issue by GenaWang** [ppwwyyxx/OpenPano#45]
@ppwwyyxx 
Thanks for your code. I used my own picture to stitch, but there were some problems. There are overlapping areas on the left and right sides of the spliced picture. Here is the picture:

![outresult1](https://user-images.githubusercontent.com/29418183/30909897-440d4ff4-a3b5-11e7-9e17-121322995bc5.jpg)

The area drawn on both sides of the red lines is the coincidence area. How to solve the panorama of the end of the region coincidence problem?

**Comment by ppwwyyxx** [comment]
It's likely that this pair of images (first and last) is the only pair that doesn't get matched since the region lacks features.

**Comment by GenaWang** [comment]
@ppwwyyxx 
Thanks for your reply.
If the first and last of these sequence images can match well. Does it mean that the panorama of the spell can be seamlessly connected?
I also tried some splicing of other sequence images. It seems that the beginning and end of the image has a coincidence area. Does the project merge the first and last of the sequence image?

**Comment by ppwwyyxx** [comment]
The head and tail are supposed to get cut properly. i.e. seeing overlapping regions is not expected.

In your image it's white wall that is hard to match.

**Comment by GenaWang** [comment]
Thanks for your reply.
