### ISSUE TITLE
Need some help installing this on windows with VS2015

### ISSUE THREAD

**Issue by gbrennon** [ppwwyyxx/OpenPano#47]
I'm having some problems with the installation of this package in windows 7 with vs2015...

When I run `cmake .` the installation fail because it can't find libjpeg... This wasn't optional??

Which version of the Eigen lib should I use? 
Because I've downloaded some versions of Eigen3 and all of them are failing on openpano build... The eigen is not coming with some Eigen3Config.cmake or eigen3-config.cmake...

One more question: libjpeg wasn't optional? My build is failing on this too

**Comment by ppwwyyxx** [comment]
Any eigen3. If you could just download from the official website, it does have cmake.

It is optional. If it fails because of this please show the log.

**Comment by gbrennon** [comment]
Here is the error from cmake

> -- Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR)
> CMake Error at C:/Users/Davi Damasio/Downloads/eigen/eigen/cmake/Eigen3Config.cm
> ake:4:
>   Parse error.  Expected a command name, got unquoted argument with text
>   "@PACKAGE_INIT@".
> Call Stack (most recent call first):
>   src/CMakeLists.txt:15 (find_package)
> 
> 
> CMake Error at src/CMakeLists.txt:15 (find_package):
>   find_package Error reading CMake code from "C:/Users/Davi
>   Damasio/Downloads/eigen/eigen/cmake/Eigen3Config.cmake".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/Davi Damasio/Desktop/OpenPano-master/CMakeFiles/CMakeOutput.l
> og".

And this is the CMakeOutput.log -> https://pastebin.com/61TyXzEL

What should I do?

Eigen3Config.cmake -> https://pastebin.com/ZcNFSZLR

**Comment by ppwwyyxx** [comment]
OK. The instruction is probably outdated. I don't use windows and don't know how to do this. 
One thing you can try is to remove eigen-related stuff in cmake:
```diff
diff --git i/src/CMakeLists.txt w/src/CMakeLists.txt
index fab5860..d50b39a 100644
--- i/src/CMakeLists.txt
+++ w/src/CMakeLists.txt
@@ -12,7 +12,6 @@ if(JPEG_FOUND)
        include_directories(${JPEG_INCLUDE_DIR})
 endif()
 
-find_package(Eigen3 REQUIRED)
 include_directories(${CMAKE_CURRENT_SOURCE_DIR})
 add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third-party/)
 
@@ -21,7 +20,7 @@ file(GLOB SOURCES feature/*.cc stitch/*.cc lib/*.cc)
 
 
 add_library(openpano ${SOURCES})       # TODO shared?
-target_link_libraries(openpano ${JPEG_LIBRARY} lodepng Eigen3::Eigen)
+target_link_libraries(openpano ${JPEG_LIBRARY} lodepng)
```

And add an extra include directory yourself, pointing to `C:/Users/Davi Damasio/Downloads/eigen/eigen/`, either though visual studio or cmake.
