### ISSUE TITLE
What to do when trees are not connected properly?

### ISSUE THREAD

**Issue by SudoHenk** [ppwwyyxx/OpenPano#49]
I have a set of photos that form a spherical image. I've tried to make a 360 image (spherical), which works fine in Image Composite Editor (from Microsoft).

However, when I try to create a spherical image with OpenPano I get the following message:
```
error: Found a tree of size 12!=14, image 5 12  are not connected well!
```

Which leads me to believe it cannot match a neighboring image to another image? Are there any config options I can play with to make this work?

Edit: Maybe this helps; an important detail is that I created images that overlap for a large part.

**Comment by ppwwyyxx** [comment]
I don't think your images overlap much with each other, especially if you compare it with the provided sample data. You would also need more overlap for rendered images than real images, because rendered images don't have many features.

**Comment by SudoHenk** [comment]
Ok, thanks!
