### ISSUE TITLE
How to compute confidence in the class of MatchInfo after matching images.

### ISSUE THREAD

**Issue by GenaWang** [ppwwyyxx/OpenPano#50]
@ppwwyyxx 
When I read the source code. I have a proble. How to calculate confidence in the MatchInfo class when I already know the number of correctly matched interior points.
The following is the output after the match, I can understand how to compute ninliers, but do not know how to compute conf?

![11](https://user-images.githubusercontent.com/29418183/32709575-5d32f066-c86c-11e7-993e-87c7ed9af3c4.png)

![12](https://user-images.githubusercontent.com/29418183/32709578-60b222fc-c86c-11e7-904a-e8d593f46709.png)

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/OpenPano/blob/d1a4aceca0d8bb151da71dc45b55050c76184643/src/stitch/transform_estimate.cc#L185-L199

**Comment by GenaWang** [comment]
@ppwwyyxx 
Thanks for your reply. What does the confidence in the MatchInfo mean? If I want to use the Surf Match. How can I compute the value of the confidence?

**Comment by ppwwyyxx** [comment]
Confidence: the feeling or belief that one can rely on someone or something.

In this context: the feeling or belief that one can rely on the match.

It is computed in the above code.
