### ISSUE TITLE
Is there any ideas on optimizing the gaussian blur (faster convolution)?

### ISSUE THREAD

**Issue by kwailamchan** [ppwwyyxx/OpenPano#53]
I tried to implement gaussian blur with cuda for reducing the runtime of gaussian blur when applying multiband blender for rendering the image, but I found that the syntax between cuda and c++11 could not be compatible when compiling the program.

Is there any ideas on how to do the faster convolution for gaussian blur? Such as the less time complexity of the algorithm? Using OpenMP? Or Multithreading with pthread, etc?

Thanks.

**Comment by ppwwyyxx** [comment]
The cheapest thing to do would be to rewrite the current blurring code with AVX.

Multi threading won't help because the program is already multi threaded at a higher level.
