### ISSUE TITLE
What is the difference between 720 degrees and 360 degrees? Have you tried splicing with fisheye pictures?

### ISSUE THREAD

**Issue by yaoweijiao** [ppwwyyxx/OpenPano#54]
What is the difference between 720 degrees and 360 degrees? Have you tried splicing with fisheye pictures?

**Comment by ppwwyyxx** [comment]
I don't understand any of the two questions.  We do not support fisheye pictures.

**Comment by yaoweijiao** [comment]
Hello, does 720 degrees of splicing do not use the wide-angle photos? How to achieve 180 degrees in the vertical direction? I would like to ask the projection model is a cylinder or sphere? Because of your superb results, can I read your dissertation or reference below?

**Comment by ppwwyyxx** [comment]
I don't know what is "720 degrees of splicing" and how it is related to this project.

If there is enough coverage of your photos on the vertical direction it can be 180 degrees. You can have 10 photos on vertical direction, not one single wide-angle photo.

It supports cylinder and sphere. For large vertical coverage it has to be sphere.

There is a blog post. http://ppwwyyxx.com/2016/How-to-Write-a-Panorama-Stitcher/

**Comment by yaoweijiao** [comment]
Ok, thank you. I understand what you mean. My idea is that each of the images used to splicing is about 180 in both vertical and horizontal directions, so that two or three images can be used to stitch a panorama.But I do not know whether to open the fisheye lens image to the plan view first, or not to do the fisheye image expansion, direct projection to the spherical surface.So I ask you how the 720-degree panorama is implemented.My English is a bit poor^_^

**Comment by crener** [comment]
I think what he wants to know is if the library compensates for the radial distortion of the lens. Since fish eye lenses are quite extreme and wouldn't look correct if used without correction.

The 720 degree thing he keeps talking about appears to be what everyone calls 360, no idea were he got 720 degrees from...

**Comment by ppwwyyxx** [comment]
@crener Thanks. That was what I thought. So I mentioned we do not support fisheye at the beginning. Anyway looks like the issue is resolved.
