### ISSUE TITLE
Compilation errors with Visual Studio 2017 

### ISSUE THREAD

**Issue by FinleyPan** [ppwwyyxx/OpenPano#56]
Hello! I have slightly modified the CMakeLists.txt(basically paths to Eigen3 and jpeglib) and successfully generated the solution file, but stuck in building the solution, it printed following errors:
**Severity	    Code	                Description	                 Project	                          File	                 Line**	  
`Error	C2036	'pano::Camera *': unknown size	openpano	e:\image stitching\openpano-master\src\stitch\incremental_bundle_adjuster.hh	47	`
`Error	C2036	'pano::Camera *const ': unknown size	openpano	D:\visual studio\VC\Tools\MSVC\14.12.25827\include\vector	957	`
`Error	C2036	'pano::Camera *const ': unknown size	openpano	D:\visual studio\VC\Tools\MSVC\14.12.25827\include\vector	963	`
`Error	LNK1104	cannot open file 'Debug\openpano.lib'	image-stitching	E:\Image Stitching\OpenPano-master\build\src\LINK	1	`
Can you help me out?

**Comment by ppwwyyxx** [comment]
Looks like it's due to Visual Studio has a different implementation of `std::vector`. I'll push a fix later.

**Comment by ppwwyyxx** [comment]
Probably fixed now. But I don't have VS to test.

**Comment by FinleyPan** [comment]
Perfect! it worked, thanks for your timely reply, Now I can freely stitched your selfies on both Windows and Ubuntu→_→. 顺便说一句，吴大神，真羡慕你在CMU的生活。

**Comment by ppwwyyxx** [comment]
Cool! :sweat_smile:

**Comment by w2xx** [comment]
@FinleyPan 可以分享下你移植到vs2017的代码吗。。我移植到vs后，编译不通过。好多关于模板的错误。如果可以，能否发到我的邮箱，wsdhjx@gmail.com，非常感谢
