### ISSUE TITLE
How to use BriefDetector instead of SIFT

### ISSUE THREAD

**Issue by MehulAjax21** [ppwwyyxx/OpenPano#63]
Hi,

I tried to use the BRIEF detector instead of the SIFT. It works well with SIFT but it is breaking with the BRIEF.
here is the output
calc_feature(): 577.267000 milliseconds.
BuildTrees: 5.841000 milliseconds.
[init_config@:253] Run with camera estimation mode.
[calc_feature@s:22] Image 3 has 602 features
[calc_feature@s:22] Image 1 has 711 features
[calc_feature@s:22] Image 0 has 544 features
[calc_feature@s:22] Image 2 has 909 features
Segmentation fault

It break during the Matching part using Flann. Is there something that I am missing or needs to be initialized?

**Comment by ppwwyyxx** [comment]
BRIEF detector in this repo is not supported.
