### ISSUE TITLE
Request for more Technical documents

### ISSUE THREAD

**Issue by MehulAjax21** [ppwwyyxx/OpenPano#64]
Hi Yuxin,

I was trying to play with the library and i was really impressed by its results. Out of curiosity, I wanted to know the exact details of why some things are done in the way they are done.
I have read the paper "Automatic Panoramic Image Stitching using Invariant Features" and also your blog on the matter.

I wanted to know is there any other document/Material/Book which explains most things. 
Example: I found you mentioned MVG in your comments a lot. Which book is that?

Regards,
Mehul Saxena

**Comment by ppwwyyxx** [comment]
MVG means Multi View Geometry. This book should contain all the details you need.

**Comment by MehulAjax21** [comment]
Thank you Yuxin for the answer. I bought the book and learnt a lot on vision geometry. I am pretty new to vision geometry so it helped me a lot.
I wanted to know the theory or mathematics behind update_proj_range() function and homo2proj() method. It will be very helpful for me.
Thanks
