### ISSUE TITLE
[Question] explanation on mathematics behind update_proj_range() function, homo2proj() and Proj2Homo(). 

### ISSUE THREAD

**Issue by MehulAjax21** [ppwwyyxx/OpenPano#65]
Hi Yuxin,

I understood most of the code base now. I just wanted brief explanation for the following functions/methods:-

update_proj_range(): How was this calculated? Is it finding the extreme points after applying transforms?
homo2proj(): I think this is the forward mapping to the projection domain
Proj2Homo(): I think it looks like inverse mapping from destination to source. 

Am I correct here?
A detailed explanation of these things will be very helpful.

Regards,
Mehul Saxena

**Comment by ppwwyyxx** [comment]
> update_proj_range(): How was this calculated? Is it finding the extreme points after applying transforms?

Yes. It was calculated by transforming all points on the edges of  the source image. This is enough to cover the entire source image.

> homo2proj(): I think this is the forward mapping to the projection domain
Proj2Homo(): I think it looks like inverse mapping from destination to source.

Yes.

**Comment by MehulAjax21** [comment]
Thanks Yuxin.
