### ISSUE TITLE
How to reuse warp and blender paras for realtime purpose?

### ISSUE THREAD

**Issue by BrownOfSummer** [ppwwyyxx/OpenPano#68]
Amazing work for images stitching and panorama.
I wonder how to reuse the warp and blender paras so that It can detect and match points, calc homo matrix once, then reuse them for video frames stitching.

**Comment by edgarmedina1801** [comment]
Nice work this OpenPano.

Interesting idea, I would like to obtain the matrix H for each transformation. If I have 5 images, it should return 5 matrices (including the first matrix image to be sure about the transformation position).

**Comment by ppwwyyxx** [comment]
Such matrices are computed in `Stitcher::estimate_camera()` or `Stitcher::build_linear_simple()`, depend on what mode you're using.
