### ISSUE TITLE
Spherical panorama

### ISSUE THREAD

**Issue by jimu1997** [ppwwyyxx/OpenPano#72]
@ppwwyyxx  Hi~thanks for sharing your work.
I want to make a spherical panorama. But I can only get a cylindrical panorama when I input the image.Would you tell me how to generate a spherical panorama?

**Comment by ppwwyyxx** [comment]
What do you mean by spherical panorama?

**Comment by jimu1997** [comment]
I want to get the picture you showed in the example [Carnegie Mellon University from 38 images.
[https://github.com/ppwwyyxx/OpenPano/blob/master/results/apple.jpg](url)
I can't get this round picture.
I can only get a rectangular picture like [https://github.com/ppwwyyxx/OpenPano/blob/master/results/CMU0-all.jpg](url)

**Comment by ppwwyyxx** [comment]
It's the `planet()` function in main.cc. You can look at the code for details.
