### ISSUE TITLE
compile with vs2017 win10

### ISSUE THREAD

**Issue by w2xx** [ppwwyyxx/OpenPano#77]
when i compile the project in vs2017，i have some problem.
1.错误	C2228	“.serialize”的左边必须有类/结构/联合	openpano	C:\Users\Administrator\Desktop\OpenPano-master\src\third-party\flann\util\serialization.h	18	
2.错误	C2065	“fdup”: 未声明的标识符	openpano	C:\Users\Administrator\Desktop\OpenPano-master\src\lib\debugutils.cc	48

**Comment by SChen1024** [comment]
在文件serialization.h中添加下列代码，位置如图所示  
[参考链接](https://www.twblogs.net/a/5b8c07f92b717718832fef81/zh-c)

测试可用

![image](https://user-images.githubusercontent.com/12789460/62004563-610da280-b159-11e9-9459-0ef3ff0c821e.png)
