### ISSUE TITLE
How is it work 'libpyopenpano'?

### ISSUE THREAD

**Issue by fadonoso** [ppwwyyxx/OpenPano#78]
Hi!!,

I see that you have a python bind but what is binding?
I really want to use yours image bundle adjustment in my python code but I don't have any idea how to do it.

Regards,
Felipe

**Comment by gbrennon** [comment]
What is needed to make this work? How can we help? @ppwwyyxx

**Comment by ppwwyyxx** [comment]
Nothing about python binding works now. I was meant to add it but do not have the time to do so.
