### ISSUE TITLE
Where can a compiled DLL (32 or 64) be downloaded?

### ISSUE THREAD

**Issue by quanjin9099** [ppwwyyxx/OpenPano#84]
Where can a compiled DLL (32 or 64) be downloaded?
Where can a compiled DLL (32 or 64) be downloaded?

**Comment by quanjin9099** [comment]
only exe in windows?

**Comment by quanjin9099** [comment]
release version can be downloaded?
and command line params?

**Comment by ppwwyyxx** [comment]
There is no exe in windows
