### ISSUE TITLE
Can't match when overlapping region is small

### ISSUE THREAD

**Issue by seabiscuit1124** [ppwwyyxx/OpenPano#85]
Could you please help us stitch the attached 2 datasets that have small overlapping regions?
Besides, if we know the extrinsic parameters between any two cameras, how to use this information in your code to accelerate?
[exampledataset.zip](https://github.com/ppwwyyxx/OpenPano/files/2764026/exampledataset.zip)

**Comment by ocean1211** [comment]
Met the same question. Any ideas? Thanks a lot!

**Comment by ppwwyyxx** [comment]
The implemented algorithms do not handle barely-overlap images like these.
