### ISSUE TITLE
I want to change out file name

### ISSUE THREAD

**Issue by carvendy** [ppwwyyxx/OpenPano#91]

**Comment by ppwwyyxx** [comment]
Change "out" to something else:
https://github.com/ppwwyyxx/OpenPano/blob/687f2fd61699c9a396bab09405bab3bd48132392/src/main.cc#L233

**Comment by pageauc** [comment]
I did some work on this and added my own code fix to allow first parameter to be the output file path including the file extension. See issue https://github.com/ppwwyyxx/OpenPano/issues/106
Claude ...
