### ISSUE TITLE
error: Cannot find config file!

### ISSUE THREAD

**Issue by ysq201466** [ppwwyyxx/OpenPano#93]
error: Cannot find config file!

**Comment by ysq201466** [comment]
./image-stitching ../../bryce_left_01.png ../../bryce_right_01.png 
error: Cannot find config file!

**Comment by ppwwyyxx** [comment]
The config file https://github.com/ppwwyyxx/OpenPano/blob/master/src/config.cfg must be in the same directory when you execute the binary.

**Comment by ysq201466** [comment]
> The config file https://github.com/ppwwyyxx/OpenPano/blob/master/src/config.cfg must be in the same directory when you execute the binary.

It has been solved. Thank you !!!!!!
