### ISSUE TITLE
How to assign the path of config.cfg file?

### ISSUE THREAD

**Issue by lee4755026** [ppwwyyxx/OpenPano#96]
How to assign the path of config.cfg file?
I configure src to system path,when using image-stitching comand in other diretory, it report error "error: Cannot find config file!"

**Comment by OpalJellyfish** [comment]
I am facing the same problem, please help!

**Comment by OpalJellyfish** [comment]
After copying the config.cfg file to the same directory as the image-stitching executable, I was able to stitch images.
