### ISSUE TITLE
Blending in y-axis direction

### ISSUE THREAD

**Issue by auriza** [ppwwyyxx/OpenPano#98]
You said in http://ppwwyyxx.com/2016/How-to-Write-a-Panorama-Stitcher/#Blending that:
>  I only used the distance along the **x axis** to calculate the weigh

How could I add blending in y axis direction also? I was stitching images horizontally and vertically in `TRANSLATE` mode. The result is not smooth vertically.

Thank you for this useful software.

![1564387280740 remmina-2019-7-30-8:58:43 169730](https://user-images.githubusercontent.com/2522330/62115724-1750c380-b2e3-11e9-9693-7450cf89387f.png)

**Comment by ppwwyyxx** [comment]
Translate mode requires inputs in a left-to-right order, so I'm surprised that you can even stitch them to a reasonable result.

The blending code is in https://github.com/ppwwyyxx/OpenPano/blob/master/src/stitch/blender.cc#L27-L37, and it blend both horizontally and vertically when inputs are unordered. You can modify it accordingly.

**Comment by auriza** [comment]
Thank you very much for your prompt response, I will try it later.

**Comment by auriza** [comment]
Definitely got a better result, but some details are still blurred.
![_result-2](https://user-images.githubusercontent.com/2522330/62557444-3205d800-b8a1-11e9-8629-df2099ed79b5.jpg)
![_result-2-detail](https://user-images.githubusercontent.com/2522330/62557499-55308780-b8a1-11e9-8861-4f643d4b6f1a.jpg)

Then, I tried `MULTIBLEND` and got a better detail. But in the big picture, there are border lines visible due to different contrast between the images. Maybe you have a clue to blend those border lines smoothly---without sacrificing the detail?
![_result-3](https://user-images.githubusercontent.com/2522330/62558121-983f2a80-b8a2-11e9-8dc4-4e7071505431.jpg)
![_result-3-detail](https://user-images.githubusercontent.com/2522330/62558401-2b786000-b8a3-11e9-93c9-85507ef6c48c.jpg)

Thank you.
